% This is an auto generated .hrl file
% Source Fields Generated by Nerlplanner version: 1.0.0

-define(SOURCE_POLICY_CASTING_IDX,"0").
-define(SOURCE_POLICY_ROUNDROBIN_IDX,"1").
-define(SOURCE_POLICY_RANDOM_IDX,"2").

-define(SOURCE_POLICY_CASTING_ATOM,casting).
-define(SOURCE_POLICY_ROUNDROBIN_ATOM,roundRobin).
-define(SOURCE_POLICY_RANDOM_ATOM,random).
