% This is an auto generated .hrl file
% Generated by Nerlplanner version: 1.0.0

-define(WORKER_KEY_MODEL_TYPE,modelType).
-define(WORKER_KEY_LAYER_SIZES_LIST,layersSizes).
-define(WORKER_KEY_LAYER_TYPES_LIST,layerTypesList).
-define(WORKER_KEY_LAYERS_FUNCTIONS,layers_functions).
-define(WORKER_KEY_LOSS_METHOD,lossMethod).
-define(WORKER_KEY_LEARNING_RATE,lr).
-define(WORKER_KEY_EPOCHS,epochs).
-define(WORKER_KEY_OPTIMIZER_TYPE,optimizer).
