VERSION = "0.0.1"
NERLNET_GLBOAL_PATH = "/usr/local/lib/nerlnet-lib/NErlNet"
NERL_PLANNER_PATH = NERLNET_GLBOAL_PATH+"/src_py/nerlPlanner"
NERLNET_LOGO_PATH = NERL_PLANNER_PATH+"/NerlnetIcon.png"
WINDOW_TITLE = "NerlPlanner"

JSON_CONTROL_LOAD_FILE_BROWSE_EVENT_KEY = 'JSON_CONTROL_LOAD_FILE_BROWSE_EVENT_KEY'
JSON_CONTROL_EXPORT_BROWSE_EVENT_KEY = 'JSON_CONTROL_EXPORT_BROWSE_EVENT_KEY'
WIN_WORKER_DIALOG_EVENT_KEY = 'WIN_WORKER_DIALOG'


KEY_SETTINGS_FREQUENCY_INPUT = '-KEY-SETTINGS-FREQUENCY-INPUT-'
KEY_SETTINGS_BATCH_SIZE_INPUT = '-KEY-SETTINGS-BATCH-SIZE-INPUT-'
KEY_SETTINGS_MAINSERVER_IP_INPUT = '-KEY-SETTINGS-MAINSERVER-IP-INPUT-'
KEY_SETTINGS_MAINSERVER_PORT_INPUT = '-KEY-SETTINGS-MAINSERVER-PORT-INPUT-'
KEY_SETTINGS_MAINSERVER_ARGS_INPUT = '-KEY-SETTINGS-MAINSERVER-ARGS-INPUT-'
KEY_SETTINGS_APISERVER_IP_INPUT = '-KEY-SETTINGS-APISERVER-IP-INPUT-'
KEY_SETTINGS_APISERVER_PORT_INPUT = '-KEY-SETTINGS-APISERVER-PORT-INPUT-'
KEY_SETTINGS_APISERVER_ARGS_INPUT = '-KEY-SETTINGS-APISERVER-ARGS-INPUT-' 
KEY_SETTINGS_NERLGUI_IP_INPUT = '-KEY-SETTINGS-NERLGUI-IP-INPUT-'
KEY_SETTINGS_NERLGUI_PORT_INPUT = '-KEY-SETTINGS-NERLGUI-PORT-INPUT-'
KEY_SETTINGS_NERLGUI_ARGS_INPUT = '-KEY-SETTINGS-NERLGUI-ARGS-INPUT-' 
KEY_SETTINGS_ADD_BUTTON = '-KEY-SETTINGS-ADD-BUTTON-'
KEY_CHECKBOX_ENABLE_NERLGUI = '-KEY-CHECKBOX-ENABLE-NERLGUI-'

KEY_WORKERS_INPUT_LOAD_WORKER_PATH = '-KEY-WORKERS-INPUT-LOAD-WORKER-PATH-'
KEY_WORKERS_LOAD_FROM_LIST_WORKER_BUTTON = '-KEY-WORKERS-LOAD-FROM-LIST-WORKER-BUTTON-'
KEY_WORKERS_SHOW_WORKER_BUTTON = '-KEY-WORKERS-SHOW-WORKER-BUTTON-'
KEY_WORKERS_NAME_INPUT = '-KEY-WORKERS-NAME-INPUT-'
KEY_WORKERS_BUTTON_ADD = '-KEY-WORKERS-BUTTON-ADD-'
KEY_WORKERS_BUTTON_VIEW = '-KEY-WORKERS-BUTTON-VIEW-'
KEY_WORKERS_BUTTON_REMOVE = '-KEY-WORKERS-BUTTON-REMOVE-'
KEY_WORKERS_LIST_BOX = '-KEY-WORKERS-LIST-BOX-'
