# Any change of this file influences autogenerated Erlang files
# Please change version of Nerlnet Planner if this file is changed

# The following definitions are also treated as atoms in Erlang
# Definition must start with lower case letter
KEY_NERLNET_SETTINGS = "nerlnetSettings"
KEY_FREQUENCY = "frequency"
KEY_BATCH_SIZE = "batchSize"
KEY_DEVICES = "devices"
KEY_CLIENTS = "clients"
KEY_WORKERS = "workers"
KEY_MODEL_SHA = "model_sha"
KEY_SOURCES = "sources"
KEY_ROUTERS = "routers"

NAME_FIELD = "name"
WORKER_MODEL_SHA_FIELD = "model_sha"
IPV4_FIELD = "ipv4"
PORT_FIELD = "port"
ARGS_FIELD = "args"
ENTITIES_FIELD = "entities"
POLICY_FIELD = "policy"
EPOCHS_FIELD = "epochs"
TYPE_FIELD = "type"
FREQUENCY_FIELD = "frequency"
WORKERS_FIELD = "workers"
DISTRIBUTED_SYSTEM_TYPE_FIELD = "distributedSystemType"
