
# Action Keys

KEY_MODEL_TYPE_LIST_BOX = '-MODEL-TYPE-LIST-BOX-'

KEY_LAYER_SIZES_INPUT = '-LAYERS-SIZES-INPUT-'
KEY_NUM_OF_LAYERS_SIZES = '-NUM-OF-LAYERS-SIZES-'
KEY_LAYER_TYPE_SELECTION = '-LAYER-TYPE-SELECTION-'
KEY_LAYER_TYPE_SELECTION_ADD = '-LAYER-TYPE-SELECTION-ADD-'
KEY_LAYER_TYPE_HELP = '-LAYER-TYPE-HELP-'
KEY_LAYER_TYPE_SELECTION_CLEAR = '-LAYER-TYPE-SELECTION-CLEAR-'
KEY_LAYER_TYPE_CODES_INPUT = '-LAYER-TYPE-CODES-INPUT-'
KEY_NUM_OF_LAYERS_TYPES = '-NUM-OF-LAYERS-TYPES-'

KEY_LAYER_METHODS_BUTTON_SELECT = '-LAYER-METHODS-BUTTON-SELECT-'
KEY_LAYER_METHODS_TEXT_SELECTION = '-LAYER-METHODS-TEXT-SELECTION-'

KEY_ACTIVATION_LAYER_SELECTION = '-ACTIVATION-LAYER-SELECTION-'
KEY_ACTIVATION_LAYER_SELECTION_ADD = '-ACTIVATION-LAYER-SELECTION-ADD-'
KEY_ACTIVATION_LAYER_HELP = '-ACTIVATION-LAYER-HELP-'
KEY_LAYER_FUNCTIONS_SELECTION_CLEAR = '-ACTIVATION-LAYER-SELECTION-CLEAR-'
KEY_LAYER_FUNCTIONS_CODES_INPUT = '-ACTIVATION-CODES-INPUT-'
KEY_LAYERS_FUNCTIONS_CODES = '-KEY-LAYERS-FUNCTIONS-CODES-'

# optimizer keys
KEY_LEARNING_RATE_INPUT = '-LEARNING-RATE-INPUT-'
KEY_OPTIMIZER_TYPE_LIST_BOX = '-OPTIMIZER-TYPE-LIST-BOX-'
KEY_LOSS_METHOD_LIST_BOX = '-LOSS-METHOD-LIST-BOX-'
KEY_EPOCHS_INPUT = '-WORKER-EPOCHS-INPUT-'


KEY_JSON_FILE_CHOSEN_DIR = '-JSON-FILE-CHOSEN-DIRECTORY'
KEY_JSON_LOAD_FILE_BUTTON_EVENT = '-JSON-FILE-LOAD-BUTTON-EVENT-'
KEY_JSON_FILE_NAME = '-JSON-FILE-NAME-'
KEY_JSON_LOAD_FILE_BROWSE_EVENT = '-JSON_LOAD_FILE_BROWSE_EVENT-'

KEY_BUTTON_EXPORT_WORKER = '-BUTTON-EXPORT-WORKER-'
KEY_CHECKBOX_WORKER_WITH_DOCUMENTATION = 'KEY-CHECKBOX-WORKER-WITH-DOCUMENTATION-'


# Layer Method Selection Dialog

KEY_LAYER_METHOD_SELECTION_DIALOG_LISTBOX_ACTIVATION = '-LAYER-METHOD-SELECTION-DIALOG-LISTBOX-ACTIVATION-'
KEY_LAYER_METHOD_SELECTION_DIALOG_LISTBOX_POOLING = '-LAYER-METHOD-SELECTION-DIALOG-LISTBOX-POOLING-'
KEY_LAYER_METHOD_SELECTION_DIALOG_LISTBOX_SCALER = '-LAYER-METHOD-SELECTION-DIALOG-LISTBOX-SCALER-'
KEY_LAYER_METHOD_SELECTION_DIALOG_LISTBOX_PROBABILISTIC = '-LAYER-METHOD-SELECTION-DIALOG-LISTBOX-PROBABILISTIC-'
KEY_LAYER_METHOD_SELECTION_TEXT = '-LAYER-METHOD-SELECTION-TEXT-'
KEY_LAYER_METHOD_SELECTION_BUTTON = '-LAYER-METHOD-SELECTION-BUTTON-'