
# Action Keys

KEY_MODEL_TYPE_LIST_BOX = '-MODEL-TYPE-LIST-BOX-'

KEY_LAYER_SIZES_INPUT = '-LAYERS-SIZES-INPUT-'
KEY_NUM_OF_LAYERS_SIZES = '-NUM-OF-LAYERS-SIZES-'
KEY_LAYER_TYPE_SELECTION = '-LAYER-TYPE-SELECTION-'
KEY_LAYER_TYPE_SELECTION_ADD = '-LAYER-TYPE-SELECTION-ADD-'
KEY_LAYER_TYPE_HELP = '-LAYER-TYPE-HELP-'
KEY_LAYER_TYPE_SELECTION_CLEAR = '-LAYER-TYPE-SELECTION-CLEAR-'
KEY_LAYER_TYPE_CODES_INPUT = '-LAYER-TYPE-CODES-INPUT-'
KEY_NUM_OF_LAYERS_TYPES = '-NUM-OF-LAYERS-TYPES-'

KEY_ACTIVATION_LAYER_SELECTION = '-ACTIVATION-LAYER-SELECTION-'
KEY_ACTIVATION_LAYER_SELECTION_ADD = '-ACTIVATION-LAYER-SELECTION-ADD-'
KEY_ACTIVATION_LAYER_HELP = '-ACTIVATION-LAYER-HELP-'
KEY_ACTIVATION_LAYER_SELECTION_CLEAR = '-ACTIVATION-LAYER-SELECTION-CLEAR-'
KEY_ACTIVATION_CODES_INPUT = '-ACTIVATION-CODES-INPUT-'
KEY_ACTIVATION_NUMOF_LAYERS = 'ACTIVATION-NUMOF-LAYERS'

# optimizer keys
KEY_LEARNING_RATE_INPUT = '-LEARNING-RATE-INPUT-'
KEY_OPTIMIZER_TYPE_LIST_BOX = '-OPTIMIZER-TYPE-LIST-BOX-'
KEY_LOSS_METHOD_LIST_BOX = '-LOSS-METHOD-LIST-BOX-'

KEY_JSON_FILE_CHOSEN_DIR = '-JSON-FILE-CHOSEN-DIRECTORY'
KEY_JSON_LOAD_FILE_BUTTON_EVENT = '-JSON-FILE-LOAD-BUTTON-EVENT-'
KEY_JSON_FILE_NAME = '-JSON-FILE-NAME-'
KEY_JSON_LOAD_FILE_BROWSE_EVENT = '-JSON_LOAD_FILE_BROWSE_EVENT-'

KEY_BUTTON_EXPORT_WORKER = '-BUTTON-EXPORT-WORKER-'
KEY_CHECKBOX_WORKER_WITH_DOCUMENTATION = 'KEY-CHECKBOX-WORKER-WITH-DOCUMENTATION-'