% This is an auto generated .hrl file
% Layers Types Generated by autogen version: 1.6.0

-define(LAYERS_TYPE_DEFAULT_IDX,"0").
-define(LAYERS_TYPE_SCALING_IDX,"1").
-define(LAYERS_TYPE_CONV_IDX,"2").
-define(LAYERS_TYPE_PERCEPTRON_IDX,"3").
-define(LAYERS_TYPE_POOLING_IDX,"4").
-define(LAYERS_TYPE_PROBABILISTIC_IDX,"5").
-define(LAYERS_TYPE_LSTM_IDX,"6").
-define(LAYERS_TYPE_RECCURRENT_IDX,"7").
-define(LAYERS_TYPE_UNSCALING_IDX,"8").
-define(LAYERS_TYPE_FLATTEN_IDX,"9").
-define(LAYERS_TYPE_BOUNDING_IDX,"10").
