-define(API_SERVER_ACTION_ACK, "ackPy").

-define(PHASE_RES_VALUES_IN_KEY_SEPARATOR, "#").
-define(PHASE_RES_WORKER_NAME_SEPERATOR, "#").
-define(PHASE_RES_VALUES_SEPERATOR, "|").
-define(PHASE_RES_DATA_SEPARATOR, "?").