
PHASE_RES_VALUES_IN_KEY_SEPARATOR = '#' # Must be identical to ?PHASE_RES_VALUES_IN_KEY_SEPARATOR in mainServerDefs.hrl

SEP_ENTITY_AND_STATS = '&'
SEP_ENTITY_OR_STATS = '|'
SEP_ENTITY_HASH_STATS = '#'
SEP_ENTITY_AT_STATS = '@'
SEP_ENTITY_COLON_STATS = ':'
SEP_ENTITY_XOR_STATS = '^'
SEP_ENTITY_DOLLAR_STATS = '$'
SEP_ENTITY_LEFT_BRACKETS_STATS = '['
SEP_ENTITY_RIGHT_BRACKETS_STATS = ']'
SEP_ENTITY_COMMA_STATS = ','
SEP_PERF_STATS = ';'

SEP_PHASE_ENTITY_DATA = '?'