import os

NErlNet_VER = 0.2
EIGEN_INCLUDE_PATH = "/usr/include/eigen3"
SO_RESULT_FILE = "NerlNIF.so"
def log_print(text):
	print("[NErlNet] "+text)

log_print("Version - "+str(NErlNet_VER))
log_print("CWD: "+os.getcwd())

if os.path.isfile(".sconsign.dblite"):
	os.remove(".sconsign.dblite")

MAIN_FILE = "test.cpp"

project_dir = os.getcwd()
build_dir = os.path.join(project_dir,'build')
lib_dir = os.path.join(project_dir,'lib')
src_dir = os.path.join(project_dir,'src')


# Set our required libraries
libraries 		= []
library_paths 	= ''
include_paths	= [os.path.join(src_dir,'include'),EIGEN_INCLUDE_PATH]
cppDefines 		= {}
cppFlags 		= ['-Wall']#, '-Werror']
cxxFlags 		= ['-std=c++11']
cxxFlags1 		= ['-fpic']

#define environment

env = Environment()
env.Append(LIBS 			= libraries)
env.Append(LIBPATH 		= library_paths)
env.Append(CPPDEFINES 	= cppDefines)
env.Append(CPPFLAGS 		= cppFlags)
env.Append(CXXFLAGS 		= cxxFlags)
env.Append(CXXFLAGS 		= cxxFlags1)
env.AppendUnique(CPPPATH = include_paths)

debug = ARGUMENTS.get('debug_info', 0)
if int(debug):
	log_print("Compiling Debug")
	env.Append(CPPFLAGS = '-g')
else:
	log_print("Compiling Release")
	env.Append(CPPFLAGS = '-O2')

SHARED_LIB_FLAG = False
shared_lib = ARGUMENTS.get('shared', False)
if shared_lib:
	SHARED_LIB_FLAG = True
	log_print("Compiling cppSANN to shared library")
	log_print(".so will be saved to lib directory")

input_src_dir = ARGUMENTS.get('src', "")
if input_src_dir:
	src_dir = input_src_dir


help_menu = ARGUMENTS.get('help', 0)
if int(help_menu):
	print("\n         Help Menu:\n------------------------------")
	print("  <Option> = 1/0")
	print("    help        - This help menu but compilation won't start")
	print("    debug       - Compiles with debug information")
	print("    shared      - Compiles as a shared library")

else:

	cpp_files = dict()

	# get all cpp from source
	for subdir, dirnames, filenames in os.walk(src_dir):
		for filename in filenames:
			if ('opennn' not in subdir) and (filename.endswith("cpp") or filename.endswith("cc")):
				if subdir not in cpp_files:
					cpp_files[subdir] = []
				cpp_files[subdir].append(filename)
	objects_list = []



	for subdir in cpp_files:
		matches = cpp_files[subdir]
		if MAIN_FILE in matches and not SHARED_LIB_FLAG:
			matches.insert(0, matches.pop(matches.index(MAIN_FILE)))	
		elif MAIN_FILE in matches and SHARED_LIB_FLAG:
			matches.remove(MAIN_FILE)
		
		for elem in matches:
			objects_list.append(env.Object(os.path.join(subdir,elem)))

	print(objects_list)
    
    
	if SHARED_LIB_FLAG:
		env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME']=1
		env.SharedLibrary(os.path.join(lib_dir,SO_RESULT_FILE), objects_list)
	else:
		env.Program(os.path.join(build_dir,"NErlNet_exec"), objects_list)
